"""
FastAPI application — the only entry point for clients.

  POST /v1/chat       ask a question            (X-API-Key required)
  POST /v1/feedback   thumbs up / down          (X-API-Key required)
  GET  /v1/vehicles   vehicle registry          (X-API-Key required)
  GET  /health        is the service ready?     (used by Docker / load balancer health checks)
  GET  /metrics       simple in-process counters
  GET  /docs          interactive API documentation (Swagger UI, generated by FastAPI)

Run locally:   uvicorn app.api.main:app --reload --port 8000
Run on a server with several worker processes:   uvicorn app.api.main:app --host 0.0.0.0 --port 8000 --workers 4

Every error response has the same shape:
  {"error": {"code": "FC-1004", "name": "RATE_LIMITED", "message": "...", "retryable": true, "request_id": "..."}}
"""
import time
import uuid
from contextlib import asynccontextmanager

from fastapi import Depends, FastAPI, Request
from fastapi.concurrency import run_in_threadpool
from fastapi.exceptions import RequestValidationError
from fastapi.responses import JSONResponse

from app.api.schemas import ChatRequest, ChatResponse, FeedbackRequest
from app.api.security import authenticate
from app.core import metrics
from app.core.config import get_settings
from app.core.errors import AppError
from app.core.logging import get_logger, request_id_var
from app.core.registry import vehicles

log = get_logger("api")

# Shared state for this worker process.
state: dict = {"pipeline": None, "startup_error": None, "startup_code": None, "inflight": 0}


# ====================================================================== startup
@asynccontextmanager
async def lifespan(app: FastAPI):
    s = get_settings()
    log.info("=" * 78)
    log.info(f"STARTING {s.app_name} v{s.app_version} | env={s.environment}")
    log.info(f"  llm={s.llm_provider} embedding={s.embedding_provider} reranker={s.reranker} "
             f"index_dir={s.index_dir}")
    log.info("=" * 78)
    t0 = time.perf_counter()
    try:
        from app.pipeline.orchestrator import CopilotPipeline
        state["pipeline"] = CopilotPipeline()
        log.info(f"STARTUP COMPLETE ✓ service ready in {time.perf_counter() - t0:.1f} s")
    except Exception as e:
        # Keep the process alive so /health can explain the problem instead of crash-looping.
        msg = f"{e.__class__.__name__}: {e}"
        state["startup_error"] = msg
        state["startup_code"] = "FC-5002" if "FC-5002" in msg else "FC-5001"
        log.critical(f"STARTUP FAILED ✗ {msg}")
    yield
    log.info("shutting down")


app = FastAPI(title="Fleet Assistance Copilot API", version=get_settings().app_version, lifespan=lifespan)


# ====================================================================== request id + access log
@app.middleware("http")
async def request_context(request: Request, call_next):
    rid = request.headers.get("X-Request-ID") or uuid.uuid4().hex[:12]
    request_id_var.set(rid)
    start = time.perf_counter()
    if request.url.path not in ("/health",):
        log.info(f"[01] gateway {request.method} {request.url.path} from {request.client.host if request.client else '-'}")
    response = await call_next(request)
    ms = round((time.perf_counter() - start) * 1000, 1)
    response.headers["X-Request-ID"] = rid
    if request.url.path not in ("/health",):
        log.info(f"[01] gateway {request.method} {request.url.path} → {response.status_code} | {ms} ms")
    metrics.incr(f"http_{response.status_code}")
    return response


# ====================================================================== error handlers
@app.exception_handler(AppError)
async def app_error_handler(request: Request, exc: AppError):
    level = log.error if exc.info.http_status >= 500 else log.warning
    level(f"{exc.code} {exc.info.name} → HTTP {exc.info.http_status}" + (f" | {exc.detail}" if exc.detail else ""))
    headers = {"Retry-After": str(exc.retry_after)} if exc.retry_after else None
    return JSONResponse(status_code=exc.info.http_status, content=exc.envelope(request_id_var.get()), headers=headers)


@app.exception_handler(RequestValidationError)
async def validation_error_handler(request: Request, exc: RequestValidationError):
    problems = [f"{'.'.join(str(p) for p in e['loc'][1:])}: {e['msg']}" for e in exc.errors()]
    log.warning(f"FC-1005 VALIDATION_FAILED → HTTP 422 | {problems}")
    return JSONResponse(status_code=422, content=AppError("FC-1005", "; ".join(problems)).envelope(request_id_var.get()))


@app.exception_handler(Exception)
async def unexpected_error_handler(request: Request, exc: Exception):
    log.exception(f"FC-5003 INTERNAL_ERROR → HTTP 500 | {exc.__class__.__name__}: {exc}")
    return JSONResponse(status_code=500, content=AppError("FC-5003").envelope(request_id_var.get()))


# ====================================================================== endpoints
def _pipeline():
    p = state["pipeline"]
    if p is None:
        raise AppError(state["startup_code"] or "FC-5001", state["startup_error"])
    return p


@app.get("/health")
def health():
    p = state["pipeline"]
    if not p:
        return JSONResponse(status_code=503, content={"status": "unhealthy", "code": state["startup_code"],
                                                      "error": state["startup_error"]})
    meta = p.retriever.meta
    return {"status": "ok", "version": get_settings().app_version, "index_version": meta.get("index_version"),
            "chunks": meta.get("chunk_count"), "embedding": meta.get("embedding"), "llm": p.llm.name,
            "reranker": p.retriever.reranker.name, "inflight": state["inflight"]}


@app.get("/metrics")
def get_metrics():
    return metrics.snapshot() | {"inflight": state["inflight"]}


@app.get("/v1/vehicles")
def list_vehicles(auth: dict = Depends(authenticate)):
    return [{"model": v["model"], "name": v["name"], "category": v["category"], "variants": v["variants"]}
            for v in vehicles()]


@app.post("/v1/chat", response_model=ChatResponse, response_model_exclude_none=True)
async def chat(body: ChatRequest, auth: dict = Depends(authenticate)):
    pipeline = _pipeline()
    log.info(f"  ├─ 1c request valid ✓ vehicle={body.vehicle_model or '-'} chars={len(body.question)}")
    # Overload guard: never accept more work than this worker can finish in time.
    limit = get_settings().max_inflight_requests
    if state["inflight"] >= limit:
        log.warning(f"  └─ 1d overload ✗ inflight={state['inflight']} limit={limit}")
        raise AppError("FC-5004", retry_after=2)
    log.info(f"  └─ 1d capacity ✓ inflight={state['inflight'] + 1}/{limit}")
    state["inflight"] += 1
    try:
        # The pipeline is ordinary (blocking) Python, so it runs in a worker thread and
        # the event loop stays free to accept other requests.
        result = await run_in_threadpool(pipeline.run, body.question, body.vehicle_model, body.variant,
                                         body.region, auth["tenant"], request_id_var.get())
    finally:
        state["inflight"] -= 1
    if not body.debug:
        result["trace"] = None
    return result


@app.post("/v1/feedback")
def feedback(body: FeedbackRequest, auth: dict = Depends(authenticate)):
    metrics.incr(f"feedback_{body.rating}")
    log.info("feedback", extra={"extra_fields": {"event": "feedback", "rated_request_id": body.request_id,
                                                 "rating": body.rating, "comment": (body.comment or "")[:500],
                                                 "tenant": auth["tenant"]}})
    log.info(f"  └─ feedback recorded | request={body.request_id} rating={body.rating}")
    metrics.emit_emf({"FeedbackUp": int(body.rating == "up"), "FeedbackDown": int(body.rating == "down")},
                     {"Environment": get_settings().environment})
    return {"status": "recorded"}
